/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "../rtl/led_test.v:1.1-29.10" *)
module led_test(sys_clk, sys_rst_n, o_led);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/led_test.v:17.15-17.29|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [9:0] _12_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/led_test.v:17.15-17.29|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [9:0] _13_;
  (* src = "../rtl/led_test.v:11.12-11.20" *)
  reg [9:0] cnt_test = 10'h000;
  (* src = "../rtl/led_test.v:7.15-7.20" *)
  output o_led;
  wire o_led;
  (* src = "../rtl/led_test.v:3.14-3.21" *)
  input sys_clk;
  wire sys_clk;
  (* src = "../rtl/led_test.v:4.14-4.23" *)
  input sys_rst_n;
  wire sys_rst_n;
  assign _12_[0] = ~cnt_test[0];
  assign _13_[1] = cnt_test[1] ^ cnt_test[0];
  assign _00_ = ~(cnt_test[1] & cnt_test[0]);
  assign _13_[2] = ~(_00_ ^ cnt_test[2]);
  assign _01_ = cnt_test[2] & ~(_00_);
  assign _13_[3] = _01_ ^ cnt_test[3];
  assign _02_ = ~(cnt_test[3] & cnt_test[2]);
  assign _03_ = _02_ | _00_;
  assign _13_[4] = ~(_03_ ^ cnt_test[4]);
  assign _04_ = cnt_test[4] & ~(_03_);
  assign _13_[5] = _04_ ^ cnt_test[5];
  assign _05_ = ~(cnt_test[5] & cnt_test[4]);
  assign _06_ = _05_ | _03_;
  assign _13_[6] = ~(_06_ ^ cnt_test[6]);
  assign _07_ = cnt_test[6] & ~(_06_);
  assign _13_[7] = _07_ ^ cnt_test[7];
  assign _08_ = ~(cnt_test[7] & cnt_test[6]);
  assign _09_ = _08_ | _05_;
  assign _10_ = _09_ | _03_;
  assign _13_[8] = ~(_10_ ^ cnt_test[8]);
  assign _11_ = cnt_test[8] & ~(_10_);
  assign _13_[9] = _11_ ^ cnt_test[9];
  (* src = "../rtl/led_test.v:12.1-19.4" *)
  always @(posedge sys_clk)
    if (!sys_rst_n) cnt_test[4] <= 1'h0;
    else cnt_test[4] <= _13_[4];
  (* src = "../rtl/led_test.v:12.1-19.4" *)
  always @(posedge sys_clk)
    if (!sys_rst_n) cnt_test[5] <= 1'h0;
    else cnt_test[5] <= _13_[5];
  (* src = "../rtl/led_test.v:12.1-19.4" *)
  always @(posedge sys_clk)
    if (!sys_rst_n) cnt_test[6] <= 1'h0;
    else cnt_test[6] <= _13_[6];
  (* src = "../rtl/led_test.v:12.1-19.4" *)
  always @(posedge sys_clk)
    if (!sys_rst_n) cnt_test[7] <= 1'h0;
    else cnt_test[7] <= _13_[7];
  (* src = "../rtl/led_test.v:12.1-19.4" *)
  always @(posedge sys_clk)
    if (!sys_rst_n) cnt_test[8] <= 1'h0;
    else cnt_test[8] <= _13_[8];
  (* src = "../rtl/led_test.v:12.1-19.4" *)
  always @(posedge sys_clk)
    if (!sys_rst_n) cnt_test[9] <= 1'h0;
    else cnt_test[9] <= _13_[9];
  (* src = "../rtl/led_test.v:12.1-19.4" *)
  always @(posedge sys_clk)
    if (!sys_rst_n) cnt_test[0] <= 1'h0;
    else cnt_test[0] <= _12_[0];
  (* src = "../rtl/led_test.v:12.1-19.4" *)
  always @(posedge sys_clk)
    if (!sys_rst_n) cnt_test[1] <= 1'h0;
    else cnt_test[1] <= _13_[1];
  (* src = "../rtl/led_test.v:12.1-19.4" *)
  always @(posedge sys_clk)
    if (!sys_rst_n) cnt_test[2] <= 1'h0;
    else cnt_test[2] <= _13_[2];
  (* src = "../rtl/led_test.v:12.1-19.4" *)
  always @(posedge sys_clk)
    if (!sys_rst_n) cnt_test[3] <= 1'h0;
    else cnt_test[3] <= _13_[3];
  assign _12_[9:1] = cnt_test[9:1];
  assign _13_[0] = _12_[0];
  assign o_led = cnt_test[9];
endmodule
