.PHONY: all sim check syn sta clean

all: check syn sta

sim:
	cd sim && make sim

check:
	cd sim && make check

syn:
	cd syn && make syn

sta:
	cd syn && make sta

clean:
	cd sim && make clean
	cd syn && make clean